spring:
  application:
    name: auth-security
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: security_info
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra


server:
  port: 1924
