spring:
  application:
    name: auth-security
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: security_info
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra


server:
  port: 1924

jwt:
  secret: pZfhYe9EJ339HWJ6bHORpAhKyZ9n3FdnxJsH7bPXSNo=
  expiration: 86400000
