version: "3.8"

services:

    cassandra:
        image: cassandra:4.1
        container_name: cassandra
        ports:
            - "9042:9042"
        networks:
            - app-network
        environment:
            - CASSANDRA_CLUSTER_NAME=HealthcareCluster
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_RACK=rack1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        volumes:
            - ./cassandra-data:/var/lib/cassandra
        restart: always

    api-gateway:
        build:
            context: ./api-gateway
        container_name: api-gateway
        networks:
            - app-network
        ports:
            - "8080:8080"
            - "5005:5005"
        environment:
            - GATEWAY_SERVICE_PORT=8080
            - JWT_SECRET=l0KdjZ1ZC1sYY5rvK8p9rseYMtItHL5mObBymV5QQ/4=
            - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        restart: always


    auth-security:
        build:
            context: ./auth-security
        container_name: auth-security
        networks:
            - app-network
        depends_on:
            - cassandra
            - api-gateway
        environment:
            - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
            - SPRING_CASSANDRA_PORT=9042
            - SPRING_CASSANDRA_KEYSPACE_NAME=security_info
            - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - SPRING_CASSANDRA_USERNAME=cassandra
            - SPRING_CASSANDRA_PASSWORD=cassandra
            - JWT_SECRET=l0KdjZ1ZC1sYY5rvK8p9rseYMtItHL5mObBymV5QQ/4=
        restart: always

    kafka:
        image: bitnami/kafka:3.6
        container_name: kafka
        ports:
            - 9092:9092
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
        networks:
            - app-network

    doctor-info:
        build:
            context: ./doctor-info
        container_name: doctor-info
        networks:
            - app-network
        depends_on:
            - cassandra
            - api-gateway
        environment:
            - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
            - SPRING_CASSANDRA_PORT=9042
            - SPRING_CASSANDRA_KEYSPACE_NAME=doctor_info
            - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - SPRING_CASSANDRA_USERNAME=cassandra
            - SPRING_CASSANDRA_PASSWORD=cassandra
        restart: always

    patient-info:
        build:
            context: ./patient-info
        container_name: patient-info
        networks:
            - app-network
        depends_on:
            - cassandra
            - api-gateway
        environment:
            - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
            - SPRING_CASSANDRA_PORT=9042
            - SPRING_CASSANDRA_KEYSPACE_NAME=patient_info
            - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - SPRING_CASSANDRA_USERNAME=cassandra
            - SPRING_CASSANDRA_PASSWORD=cassandra
        restart: always

    appointment-services:
        build:
            context: ./appointment-services
        container_name: appointment-services
        networks:
            - app-network
        depends_on:
            - cassandra
            - api-gateway
            - doctor-info
            - patient-info
            - kafka
        environment:
            - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
            - SPRING_CASSANDRA_PORT=9042
            - SPRING_CASSANDRA_KEYSPACE_NAME=appointment_info
            - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
            - SPRING_CASSANDRA_USERNAME=cassandra
            - SPRING_CASSANDRA_PASSWORD=cassandra
            - KAFKA_BOOTSTRAP_SERVER=kafka:9092
            - KAFKA_TOPIC=appointments
        restart: always

    notification-services:
        build:
            context: ./notification-services
        container_name: notification-services
        networks:
            - app-network
        depends_on:
            - appointment-services
            - kafka
        environment:
            - KAFKA_BOOTSTRAP_SERVER=kafka:9092
            - KAFKA_GROUP_ID=appointment-notifications-group
            - KAFKA_TOPIC=appointments
            - MAIL_SERVER_HOST=smtp.gmail.com
            - MAIL_SERVER_PORT=587
            - MAIL_SERVER_USERNAME=noreplyrajat@gmail.com
            - MAIL_SERVER_PASSWORD=password
        restart: always


networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
        driver: local
    cassandra-data:
        driver: local

